navbar_title: American Indian Law Alliance
image: /img/alfie-jacques-award-banner.jpg
navbar:
 - nav: About
   link: /about

footer: 
 - icon: fa-brands fa-facebook
   link: https://facebook.com/americanindianlawalliance
   title: Follow American Indian Law Alliance on Facebook
 - icon: fa-brands fa-instagram
   link: https://www.instagram.com/americanindianlawalliance/
   title: Follow American Indian Law Alliance on Instagram
 - icon: fa-brands fa-linkedin
   link: https://www.linkedin.com/company/american-indian-law-alliance/
   title: Follow American Indian Law Alliance on LinkedIn
 - icon: fa-brands fa-twitter
   link: https://twitter.com/AILAnyc
   title: Follow American Indian Law Alliance on Twitter
 - icon: fa-brands fa-youtube
   link: https://www.youtube.com/@aila-ngo
   title: Follow American Indian Law Alliance on YouTube
 - icon: fa-solid fa-globe
   link: https://aila.ngo
   title: American Indian Law Alliance Official Site
 - icon: fa-solid fa-envelope
   link: "mailto:aila@aila.ngo"
   title: Sent Email to American Indian Law Alliance

copyrights:
 text1: CC BY-NC 4.0 by
 text2: American Indian Law Alliance
 text2_link: https://aila.ngo
 text3: built with
 text4: 11ty
 text4_link: https://11ty.dev
